[]{#sessions}

# I kursuse sisu

## Avaldised ja arvuhulgad

### Õpitulemused

\multicolsbegin

Kursuse lõpus õpilane:

1. leiab hulkade ühendi, ühisosa ja antud hulga osahulga;
2. selgitab naturaalarvude hulga N, täisarvude hulga Z, ratsionaalarvude hulga Q,
irratsionaalarvude hulga I ja reaalarvude hulga R omadusi ja nende hulkade kuuluvusseoseid,
märgib arvteljel reaalarvude piirkondi;
3. esitab arvu juure ratsionaalarvulise astendajaga astmena ja vastupidi;
4. sooritab tehteid astmete ning võrdsete juurijatega juurtega;
5. teisendab lihtsamaid ratsionaal- ja irratsionaalavaldisi (kaks tehet ja sulud);
6. näeb ja lahendab arvutuste ja teisenduste abil lahenduvaid reaalelulisi ja teaduslikke
probleeme (sh protsentülesanded). Tõlgendab ja esitleb saadud tulemusi.[@gmnaasiumi].

\multicolsend

## Kalender

### 2024-9-12

Tegurdasime.

Osalesid milena ja anna.

### 2024-9-19

Tegurdasime.

Osalesid arina, anja, Nickita Serdiuk ja virko Boitrov.

### 2024-9-19

Teisendasime perioodilisi kümnendosamäärasid harilikeks.

### 2024-9-19

### 2024-9-19

Lahendasime eri arvutüüpide seoste ülesandeid. Koju jäid lahendada põhiõpiku ülesanded 23 ja 24, arinale ka 22.

### 2024-9-26

Lahendasime X õpikust 24 ja 37'st esimesed kolm.

Osalesid virko, arina, jaroslav.

### 2024-9-26

Lahendasime X õpikust 37 edasi.

Osalesid virko, arina, nickita, anja.

### 2024-9-26

Tegime arvutusi 82-83.

### 2024-9-26

Harjutasime juure teisendamist astendajaks ja vastupidi. Kombineerisime. Osa harjutusi jäid koju lahendada.

Osalesid anja, jaroslav, virko ja nickita.

### 2024-10-10

Andsin ChatGPT'le järgmised käsud ja siis me lahendasime kõik komplektid, välja arvatud viimase ülesande, aga seda tüüpi ülesannet olime juba lahendanud ka:

Koosta 16 ülesannet õppimaks, harjutamaks ja enesekontrolliks järgmise õpiväljundi suhtes: selgitab naturaalarvude hulga N, täisarvude hulga Z, ratsionaalarvude hulga Q,
irratsionaalarvude hulga I ja reaalarvude hulga R omadusi 

Koosta 16 ülesannet õppimaks, harjutamaks ja enesekontrolliks järgmise õpiväljundi suhtes: selgitab naturaalarvude hulga N, täisarvude hulga Z, ratsionaalarvude hulga Q,
irratsionaalarvude hulga I ja reaalarvude hulga R kuuluvusseoseid

Koosta 16 ülesannet õppimaks, harjutamaks ja enesekontrolliks järgmise õpiväljundi suhtes: esitab arvu juure ratsionaalarvulise astendajaga astmena ja vastupidi;

Kõik neli õppesessiooni olid. Esimeses kahes osales ainult Virko. Kolmandasse liitus Anna Saffran ja viimasesse tuli ka Jaroslav. Sellest sessioonist oluline osa kulutati joonistamiseks.

### 2024-10-17

Esimeses sessioonis oli ainult Virko. Ta joonistas ja ma kirjutasin testiülesandeid. Seejärel ta asus testi sooritama.

Teise sessiooni lisandus Mykyta, kes ka alul proovis testi sooritada, aga kuna te eelmine kord polnud, siis harjutasime 16 ülesannet tahvlile ja Virko mõtles kaasa. Virkol pea valutas ja ta lahkus.

Sisse kiikas Jaroslav, kes näitas füüsika ühikutevahelise teisendamise ja kinemaatika ülesandeid. Mykyta lahendas lõpuni ja asus testi sooritama.

Mykyta sooritas testi lõpuni ning lahendasime temaga tahvlile arvuhulkade ülesandeid, nii et järgmiseks korraks on ta valmis seda testi sooritama. Jaroslav mõtles kaasa ja samuti tegi enda tabeli arvuhulkade ja näidisarvude kohta.

Mykyta tegi kõik teisendused ja arvutused, kuid jättis võrdlemata ja selgitamata. A.

### 2024-10-31

Virkoga lahendasime tema vigaselt lahendatud testiülesanded ja ta asus tegema testi arvu juure esitamiseks ratsionaalarvulise astendajaga ja vastupidi kohta.

Selgus, et ta ei saa hakkama negatiivsest harilikust osamäärast astendajaga. Nii et järgmise õppesessiooni kasutasime selleks, et sammhaaval seda selgitada ning lõpuks ta suutis teisendada õigele kujule.

Tegime vaheaja, mille kestel ta joonistas nutitelefoni ekraanilt seinaekraanile maha kujutist.

Kolmandas sessioonis tegime koos testi lõpuni. Saavutus: A.

### 2024-11-7

Esimeses sessioonis õpilasi polnud.

Teises sessioonis on anna safran ja virko. anna asus tegema arvu juure esitamise ratsionaalarvulise astendajaga ja vastupidi testi. Jõudis teha 12 ülesannet. Virkole õpetasin tehteid astmete ja võrdsete juurijatega juurtega. Tegi kuus ülesannet.

Kolmandas sessioonis anna jätkas testiga ja lõpetas. Asus sooritama testi naturaalarvude, täisarvude, ratsionaalarvude, irratsionaalarvude ja reaalarvude kuuluvusseoste kohta. jõudis teha 5 ülesannet. virkoga lahendasime üheksandani. jaroslav liitus ja asus mõtlema kaasa virkole.

Neljandas lahendasime kõik koos 11'ndani.

Anna testitulemus "Tehete sooritamine võrdsete juurijatega juurtega" kohta: MA.

### 2024-11-14

Anna teatas, et ta esimeses kahes õppesessioonis ei osale, kuna peab järelvastama.

Esimeses pole üldse ühtki õpilast.

Teises sessioonis lahendasime "Õpilane sooritab tehteid võrdsete juurijatega juurtega" ülesanded Virkoga lõpuni.

Kolmandas sessioonis lahendasime esimese ülesande teemal "Õpilane näeb ja lahendab arvutuste ja teisenduste abil lahenduvaid reaalelulisi ja teaduslikke
probleeme (sh protsentülesanded). Tõlgendab ja esitleb saadud tulemusi."

Neljandas mängis Virko nutitelefoniga, liitus jaroslav ja lahendasime kuni 9. ülesandeni.

### 2024-11-21

Anna Saffran tuli ja tegime kaks esimest sessiooni läbi tema vigaseid testi "Tehete sooritamine võrdsete juurijatega juurtega" ülesandeid. Teise sessiooni liitus ka virko, kuid tegeles kõrvalise tegevusega.

Kolmandas sessioonis Annat enam polnud, kuna ta teatas ette, et läheb repetiitoriga kohtuma. Virkoga lahendasime ülesandeid teemal "arvutuste ja teisenduste abil reaaleluliste ja teaduslike probleemide lahendamist, sealhulgas protsentülesandeid, ning tulemuste tõlgendamist ja esitlemist", kuni saabus Jaroslav, kes võttis neljandaks sessiooniks tahvlile lahendamise üle, misjärel Virko tegeles edasi kõrvalise tegevusega. jõudsime kenasti ülesanded lõpuni lahendada.

### 2024-11-28

Esimeses sessioonis õpilasi polnud.

Teiseks sessiooniks saabus virko ja asus lahendama testi "Tehete sooritamine võrdsete juurijatega".

Kolmandaks sessiooniks lisandus anna saffran. Arutasime tema testi arvuhulkade kuuluvusseoste lahendusi.

Neljandaks sessiooniks lisandusid jaroslav ja mykyta. jaroslav asus tegema testi arvuhulkade omaduste kohta. mykyta asus tegema sama testi. virko jätkas. anna sai 8 /16 ehk A. jaroslav tegi tahvlile, tegin pildi. Virko ei suutnud mitte ühtki õiget lahendust pakkuda, seega MA. mykyta lõpetas tulemusega A.

### 2024-12-5

Virko teatas, et seekord ei osale ja hakkabki üle nädala osalema.

Esimeses sessioonis publikut polnud.

Teises sessioonis polnud ka publikut. Jaroslav käis selle lõpus korraks külas ja ütles, et kolmandasse ei tule, sest riigikaitse, aga neljandasse tuleb. Anna jalutas mööda ja ütles, et tuleb veidi hiljem.

Kolmandasse sessiooni ei tulnud keegi.

Neljandas sessioonis olin 11 min üksi ja lahkusin.

Ei jõudnud lahkuda kaugele, kui Jaroslav mind kutsus ja nii me alustasime neljandat õppesessiooni. Jõudsin talle selgitada tema testi esimesed viis ülesannet.

### 2024-12-12

Esimeses õppesessioonis polnud õpilasi. Vestlesin virkoga ja ta ütles, et läheb hoopis saksa keelt õppima ja pärast tuleb.

Teises õppesessioonis võtsime virkoga ette ülesannete kogust ülesande 2.25. Selle esimese alamülesande kallal pusisime. Pidin selgitama, kuidas üldse osamäärasid liita. Jõudsime seega esimese tehtega nii kaugele, et ta kirjutas ühise jaoturi ning kummagi tihendaja.

Kolmandas õppesessioonis jõudsime nii kaugele, et tihenditega läbikorrutamise tulemusena oli ühine uus loendur olemas.

Neljandasse õppesessiooni tuli ka jaroslav, kes võttis virkolt üle ja me jõudsime ainult kõik üksliikmed läbi korrutada. virko mängis mingit telomängu.

# 2024-12-19

Üldse õpilasi polnud.

# 2025-1-9

Essas kedagi pold.

Teisest alates oli virko ja asus tegema sooritamise testi. Aitan teda sammhaaval mõne ülesande puhul. Tal oli nt meelest läinud, kuidas liita harilikke osamäärasid. Tegime kõik ülejäänud sessioonid. Mida rohkem tegime, ta väsis ja ei suutnud enam sama tüüpi ülesandeid lahendada.

# 2025-1-16

Mitte keegi ei osalenud.

# 2025-1-23

Esimeses sessioonis Virko lõpetas testi *Tehete sooritamine võrdsete juurijatega juurtega* ja arvestasin selle arvestatuks.

Teises sessioonis Virko alustas testiga reaaleluliste probleemidega ning jõudis läbida kaks esimest taset.

Kolmandas sessioonis tegime reaaleluliste probleemide testi lõpuni ja arvestasin talle selle tehtuks.

Neljandas sessioonis alustas Virko testiga arvuhulkade omaduste kohta ja jõudsime üheksa ülesannet lahendatud.

# 2025-2-13

Esimeses polnud kedagi.

Teise tuli jaroslav. Asus sooritama testi teemal "sooritab tehteid astmete ning võrdsete juurijatega juurtega". Ta ei osanud ja asusime sammhaaval tahvlile vihjete abil tegema.

Kolmandasse liitus mykyta ning panin nad mõlemad koos tegema. Jõudsime lahendada kaheksanda ülesandeni.

Neljandas jätkasime testisooritust. Lõpuni. Mõlemale: sooritatud. mykyta alustas protsentülesannete testi sooritamist, jaroslav jätkas eelmise testi ülelahendamist. mykyta läbis protsentülesannete testi: sooritatud.
